steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 
             'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}', '.']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 
             'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}' ]

    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'gcloud'
      args: ['beta', 'run', 'deploy', '${_SERVICE_NAME}', 
             '--platform', 'managed', '--region', '${_REGION}',
             '--image', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}',
             '--tag', 'pr-${_PR_NUMBER}',
             '--no-traffic']
    
    - name: 'gcr.io/${PROJECT_ID}/set-check-status'
      args: ['--project-id', '${PROJECT_ID}',
             '--region', '${_REGION}',
             '--service', '${_SERVICE_NAME}',
             '--tag', 'pr-${_PR_NUMBER}',
             '--repo-name', '${_GITHUB_USER}/${REPO_NAME}',
             '--commit-sha', '${SHORT_SHA}']

substitutions: 
    _SERVICE_NAME: myservice
    _REGION: us-central1
